menu:
  - name: Notes
    url: /notes
  - name: Home
    url: /
  - name: Archives
    url: /archives
  - name: Categories
    url: /categories
  - name: Tags
    url: /tags
  - name: About
    url: /about
  - name: RSS
    url: /rss.xml
sidebar: # Sidebar
  enable: true 
  widgets:
    - search # Search
    - notice # Notice
    - categories # Categories
    - tags # Tags
    - links # Links

  numlimit: # Limit the number of items shown in the sidebar
    categories: 5
    tags: 10
    
  links:
    - name: bç«™ä¸»é¡µ
      url: https://space.bilibili.com/1515974075?spm_id_from=333.1387.fans.user_card.click
    - name: githubä¸»é¡µ
      url: https://github.com/m310ct
    - name: ç”µå­é‚®ç®±
      url: mailto:3667864590@qq.com
    - name: Hacker Notes
      url: https://www.m310ct.com/notes
  notice: # å…¬å‘Šæ å†…å®¹
    enable: true # è®¾ç½®ä¸º true å¯ç”¨ï¼Œfalse ç¦ç”¨
    content: "
  ğŸ‰ æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ï¼</br>
     è¯·æŸ¥çœ‹æœ€æ–°æ–‡ç« ~" # å…¬å‘Šæ æ˜¾ç¤ºçš„å†…å®¹

toc: #æ–‡ç« ç›®å½•
  enable: true
